### ISSUE TITLE
scrolling problem in grades

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-client#26]
Currently in the mat-tab-group is a bug in the scrolling behavior: (only the right scroll bar should be there)
![scrollingBug](https://user-images.githubusercontent.com/67689103/176027574-18dd1ed6-e870-4b52-8c40-6268638edfcb.png)

I found that this is solvable when overwriting the css class "mat-tab-body-content". The height needs to be set to "max-content" and the overflow to "hidden".
Unfortunately I could only implement this in the browsers dev tools and not directly in the project. This needs to be fixed as soon as there is time.

**Comment by EricWermelinger** [comment]
Implemented in #27
