### ISSUE TITLE
map grades screen to url

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-client#28]
Currently the grades screen is represented behind a single URL. This makes it impossible to share any data and is also weird for users. When the users want to go one step back on the page, they'll end up on an entirely other page.  
At least make an URL for the grades details view. This way you don't have to click the "x" in the top corner when wanting to return to the grades overview page.

**Comment by EricWermelinger** [comment]
I tried to implement this today, however, it looks almost impossible to me to implement it on the current structure without changing everything. Maybe we should just leave with it ;-)

**Comment by EricWermelinger** [comment]
Can we close this issue? :)

**Comment by M1chaCH** [comment]
🤔🫡
