### ISSUE TITLE
New endpoint for grades 

### ISSUE THREAD

**Issue by OliUmbi** [moreach/teachu-client#33]
I have changed the endpoint for grades. 
It should contain roughly the same information as before, but slightly restructured. 
Note: teacher responses should be resolved from a component, since it's just `externalUser` endpoint

**Comment by M1chaCH** [comment]
@OliUmbi I think the frontend is missing the current students id. Because the /grade GET endpoint requires the id of the student.  
But otherwise I prefer the naming of this version.

**Comment by M1chaCH** [comment]
grades work now 100% with the new endpoint
