### ISSUE TITLE
User Settings - Profile Image find better way

### ISSUE THREAD

**Issue by EricWermelinger** [moreach/teachu-client#38]
![image](https://user-images.githubusercontent.com/55582419/182543650-df4497b5-544c-476d-a54e-e135ccdbb87c.png)

Today, the situation is not clear for the user when an profile image is set. We should either:

- Show existing Profile Image in Control
- Change to other control (just a button?) which says "Change Profile Image"

**Comment by M1chaCH** [comment]
will be improved with this merge  #40
