### ISSUE TITLE
UserSettings AutoSave

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-client#42]
Changes to autosaved values aren't saved when changing the page immediately after changing a value. 

Recreate: 
1. change phone number or darktheme
2. change page immediately
3. changes are never saved in the api 

The reason for that is the lifetime of the UserSettings component. The component is destroyed after page change. 

Solution: 
Move autosave functionality including the "debounceTime" to a singleton service. (ex. UserServise)

**Comment by EricWermelinger** [comment]
Fixed in: https://github.com/moreach/teachu-client/tree/bugfix/fix-timetable
