### ISSUE TITLE
mobile view

### ISSUE THREAD

**Issue by M1chaCH** [moreach/teachu-client#52]
mobile ui problems: 
1. page to high everywhere
2. can't add absence because plus button does not work (most likely covered by three dots div because it works with 0 absences)

**Comment by M1chaCH** [comment]
page to high actually only happens on IOS. 
Found some workarounds but didn't manage to implement them. 
@OliUmbi you are my last hope

**Comment by M1chaCH** [comment]
and since you are already here. What is this (also only IOS): 

https://user-images.githubusercontent.com/67689103/191989007-8d39345c-2c73-41e0-8717-b12b3e8dbd84.MP4

**Comment by OliUmbi** [comment]
WTF I have no idea what causes this, but I hope it will be resolved with the new implementation
